package com.solutioncube.common;

public enum ExecutionType {

	STATIC_COLLECTIONS,
	
	DAILY_COLLECTIONS,
	
	BULK_DATA_ONLY_WITH_SINCE_PARAM,
	
	BULK_DATA_WITH_BOTH_SINCE_AND_TILL_PARAM,
	
	PROCESS_DAILY_COLLECTIONS,
	
	PROCESS_CONVERSION;
}
