package com.solutioncube.common;

public enum TaskType {

	TASKS_WHICH_STATIC,
	
	TASKS_WHICH_DAILY,
	
	TASKS_WHICH_ONLY_WITH_SINCE_PARAM_FOR_INSERT_BULK_DATA,
	
	TASKS_WHICH_WITH_BOTH_SINCE_AND_TILL_PARAM_FOR_INSERT_BULK_DATA;
}
